import { type NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";
import HomeLayout from "~/Layouts/HomeLayout";
import { api } from "~/utils/api";
import dynamic from "next/dynamic";

const Chart = dynamic(() => import("~/components/Chart/Chart"), { ssr: false });

const Profile: NextPage = () => {
  const { data: sessionData } = useSession();
  const { data, isLoading } = api.example.getExpenses.useQuery(undefined, {
    enabled: sessionData?.user !== undefined,
  });
  const isLoggedOut = !sessionData?.user;

  return (
    <>
      <Head>
        <title>Profile</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomeLayout>
        <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[4rem]">
          Profile
        </h1>
        <>
          {isLoggedOut ? (
            <div className="text-gray-500 dark:text-white">
              Please login first to see your expenses chart.
            </div>
          ) : isLoading ? (
            <div className="text-gray-500 dark:text-white">loading...</div>
          ) : null}
          {data && data?.length < 1 ? (
            <div className="text-gray-500 dark:text-white">
              You can add new items by tapping the plus icon below
            </div>
          ) : (
            data && (
              <div className="flex w-full flex-col gap-2 pb-8">
                <Chart data={data} />
              </div>
            )
          )}
        </>
      </HomeLayout>
    </>
  );
};

export default Profile;
